# Advanced Machine Learning and MLOps: Tourism Package Prediction

## Business Context
"Visit with Us" wants to identify customers who are likely to purchase the newly introduced Wellness Tourism Package before the sales team contacts them. A machine learning driven workflow can improve targeting, reduce manual effort, and support better campaign planning.

## Objective
The objective of this project is to build and deploy an end-to-end MLOps pipeline that:
- registers the dataset in the Hugging Face Dataset Hub,
- prepares train and test data directly from the registered dataset,
- trains and tunes a predictive model,
- registers the best model in the Hugging Face Model Hub,
- deploys the model using Streamlit on Hugging Face Spaces, and
- automates the workflow using GitHub Actions.

## Project Folder Structure
```text
TourismPackage/
├── tourism_mlops_project_aligned.ipynb
├── data/
│   ├── tourism.csv
│   ├── train.csv
│   └── test.csv
├── model_building/
│   ├── model.pkl
│   ├── label_encoders.pkl
│   ├── best_params.json
│   └── tuning_results.csv
├── deployment/
│   ├── app.py
│   ├── requirements.txt
│   ├── Dockerfile
│   └── push_to_space.py
└── .github/
    └── workflows/
        └── pipeline.yml
```

## 1. Data Registration

In this section:
- a master project folder and `data` subfolder are created,
- the raw dataset is stored in the local project structure,
- the dataset is registered in the Hugging Face Dataset Hub.

This helps centralize the data source and makes the pipeline reproducible.

In [7]:
from google.colab import drive
drive.mount('/content/drive')

import os

BASE_PATH = "/content/drive/MyDrive/GreatLearnings/TourismPackage"
DATA_PATH = f"{BASE_PATH}/data"
MODEL_BUILD_PATH = f"{BASE_PATH}/model_building"
DEPLOYMENT_PATH = f"{BASE_PATH}/deployment"
GITHUB_WORKFLOW_PATH = f"{BASE_PATH}/.github/workflows"

for path in [BASE_PATH, DATA_PATH, MODEL_BUILD_PATH, DEPLOYMENT_PATH, GITHUB_WORKFLOW_PATH]:
    os.makedirs(path, exist_ok=True)

print("Project folders are ready.")
print("Base path:", BASE_PATH)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project folders are ready.
Base path: /content/drive/MyDrive/GreatLearnings/TourismPackage

In [8]:
import pandas as pd

# Load the raw dataset from Drive
raw_df = pd.read_csv(f"{DATA_PATH}/tourism.csv")
print("Raw dataset shape:", raw_df.shape)
raw_df.head()

Raw dataset shape: (4128, 21)

,Unnamed: 0,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,...,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,...,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,...,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,...,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,...,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,...,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0

In [9]:
!pip install -q huggingface_hub

In [10]:
from huggingface_hub import login

# Replace with your own token before execution
HF_TOKEN = "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"
login(HF_TOKEN)

In [11]:
from huggingface_hub import create_repo, upload_file, whoami

print("Logged in user:", whoami()["name"])

# Dataset repository
repo_id = "subhaspace/TourismPackage"   # replace only if your dataset repo is different
create_repo(repo_id=repo_id, repo_type="dataset", exist_ok=True)

upload_file(
    path_or_fileobj=f"{DATA_PATH}/tourism.csv",
    path_in_repo="tourism.csv",
    repo_id=repo_id,
    repo_type="dataset"
)

print(f"Raw dataset registered at: https://huggingface.co/datasets/{repo_id}")

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Logged in user: subhaspace
Raw dataset registered at: https://huggingface.co/datasets/subhaspace/TourismPackage

### Observation
The master folder and `data` subfolder were created successfully. The raw dataset was uploaded to the Hugging Face Dataset Hub so that the rest of the workflow can load the data directly from the registered source.

## 2. Data Preparation

In this section:
- the raw dataset is loaded directly from the Hugging Face dataset space,
- unnecessary columns are removed,
- the cleaned dataset is split into train and test sets,
- the train and test files are saved locally and uploaded back to Hugging Face.

In [12]:
# Load the dataset directly from Hugging Face Dataset Hub
df = pd.read_csv(f"https://huggingface.co/datasets/{repo_id}/resolve/main/tourism.csv")
print("Dataset loaded from HF:", df.shape)
df.head()

Dataset loaded from HF: (4128, 21)

,Unnamed: 0,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,...,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,...,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,...,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,...,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,...,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,...,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0

In [13]:
# Data cleaning
df = df.copy()
df.drop(columns=["Unnamed: 0", "CustomerID"], inplace=True, errors="ignore")

print("Shape after removing unnecessary columns:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())

Shape after removing unnecessary columns: (4128, 19)

Missing values:
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split

X = df.drop("ProdTaken", axis=1)
y = df["ProdTaken"]

X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

train_df = pd.concat([X_train_raw, y_train], axis=1)
test_df = pd.concat([X_test_raw, y_test], axis=1)

train_df.to_csv(f"{DATA_PATH}/train.csv", index=False)
test_df.to_csv(f"{DATA_PATH}/test.csv", index=False)

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Train shape: (3302, 19)
Test shape: (826, 19)

In [15]:
# Upload train and test datasets back to Hugging Face
upload_file(
    path_or_fileobj=f"{DATA_PATH}/train.csv",
    path_in_repo="train.csv",
    repo_id=repo_id,
    repo_type="dataset"
)

upload_file(
    path_or_fileobj=f"{DATA_PATH}/test.csv",
    path_in_repo="test.csv",
    repo_id=repo_id,
    repo_type="dataset"
)

print(f"Train and test files uploaded to: https://huggingface.co/datasets/{repo_id}")

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.
No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Train and test files uploaded to: https://huggingface.co/datasets/subhaspace/TourismPackage

### Observation
The dataset was loaded directly from the Hugging Face dataset space, cleaned by removing unnecessary identifier columns, and split into training and testing sets using stratified sampling. The generated train and test files were then uploaded back to the Hugging Face dataset space for reuse.

## 3. Model Building with Experimentation Tracking

In this section:
- train and test data are loaded from Hugging Face,
- categorical columns are encoded,
- a Random Forest model is tuned using GridSearchCV,
- tuned parameters are logged,
- the model is evaluated,
- the best model is saved and registered in the Hugging Face Model Hub.

In [16]:
# Load train and test data from Hugging Face
train_df = pd.read_csv(f"https://huggingface.co/datasets/{repo_id}/resolve/main/train.csv")
test_df = pd.read_csv(f"https://huggingface.co/datasets/{repo_id}/resolve/main/test.csv")

print("Train:", train_df.shape)
print("Test:", test_df.shape)

Train: (3302, 19)
Test: (826, 19)

In [17]:
import joblib
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in train_df.select_dtypes(include="object").columns:
    le = LabelEncoder()
    train_df[col] = le.fit_transform(train_df[col].astype(str))
    test_df[col] = le.transform(test_df[col].astype(str))
    label_encoders[col] = le

ENCODER_PATH = f"{MODEL_BUILD_PATH}/label_encoders.pkl"
joblib.dump(label_encoders, ENCODER_PATH)

print("Categorical columns encoded and encoders saved.")

Categorical columns encoded and encoders saved.

In [18]:
X_train = train_df.drop("ProdTaken", axis=1)
y_train = train_df["ProdTaken"]

X_test = test_df.drop("ProdTaken", axis=1)
y_test = test_df["ProdTaken"]

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

Training features: (3302, 18)
Testing features: (826, 18)

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [50, 100, 150],
    "max_depth": [5, 10, None],
    "min_samples_split": [2, 5]
}

rf = RandomForestClassifier(random_state=42, class_weight="balanced")

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_

print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:", grid_search.best_score_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
Best Parameters: {'max_depth': None, 'min_samples_split': 5, 'n_estimators': 100}
Best CV Score: 0.9018803842237085

In [20]:
import json

# Log tuned parameters and CV results
best_params_path = f"{MODEL_BUILD_PATH}/best_params.json"
tuning_results_path = f"{MODEL_BUILD_PATH}/tuning_results.csv"

with open(best_params_path, "w") as f:
    json.dump(grid_search.best_params_, f, indent=4)

pd.DataFrame(grid_search.cv_results_).to_csv(tuning_results_path, index=False)

print("Best parameters saved at:", best_params_path)
print("Tuning results saved at:", tuning_results_path)

Best parameters saved at: /content/drive/MyDrive/GreatLearnings/TourismPackage/model_building/best_params.json
Tuning results saved at: /content/drive/MyDrive/GreatLearnings/TourismPackage/model_building/tuning_results.csv

In [21]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

preds = best_model.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, preds))
print("\nClassification Report:\n")
print(classification_report(y_test, preds))
print("Confusion Matrix:\n", confusion_matrix(y_test, preds))

Test Accuracy: 0.9188861985472155

Classification Report:

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       667
           1       0.89      0.66      0.76       159

    accuracy                           0.92       826
   macro avg       0.91      0.82      0.85       826
weighted avg       0.92      0.92      0.91       826

Confusion Matrix:
 [[654  13]
 [ 54 105]]

In [22]:
MODEL_PATH = f"{MODEL_BUILD_PATH}/model.pkl"
joblib.dump(best_model, MODEL_PATH)

print("Best model saved at:", MODEL_PATH)

Best model saved at: /content/drive/MyDrive/GreatLearnings/TourismPackage/model_building/model.pkl

In [23]:
# Register the best model in Hugging Face Model Hub
repo_model = "subhaspace/TourismPackage"   # replace only if your model repo is different
create_repo(repo_id=repo_model, repo_type="model", exist_ok=True)

upload_file(
    path_or_fileobj=MODEL_PATH,
    path_in_repo="model.pkl",
    repo_id=repo_model,
    repo_type="model"
)

upload_file(
    path_or_fileobj=ENCODER_PATH,
    path_in_repo="label_encoders.pkl",
    repo_id=repo_model,
    repo_type="model"
)

upload_file(
    path_or_fileobj=best_params_path,
    path_in_repo="best_params.json",
    repo_id=repo_model,
    repo_type="model"
)

print(f"Model registered at: https://huggingface.co/{repo_model}")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  .../model_building/model.pkl:  95%|#########5| 5.22MB / 5.47MB

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ilding/label_encoders.pkl: 100%|##########| 1.87kB / 1.87kB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Model registered at: https://huggingface.co/subhaspace/TourismPackage

### Observation
The Random Forest model was tuned using GridSearchCV. The tuned hyperparameters were logged in a JSON file and the full tuning results were saved as a CSV file. The best model was evaluated on the test set and then registered in the Hugging Face Model Hub along with the label encoders.

## 4. Model Deployment

In this section:
- deployment files are generated,
- a Dockerfile defines the runtime environment,
- a requirements file defines dependencies,
- the Streamlit application loads the saved model from the Hugging Face Model Hub,
- a helper script is created to push deployment files to Hugging Face Space.

In [24]:
app_py = '''
import os
import joblib
import pandas as pd
import streamlit as st
from huggingface_hub import hf_hub_download

st.set_page_config(page_title="Tourism Package Prediction", page_icon="✈️", layout="centered")

MODEL_REPO_ID = os.getenv("MODEL_REPO_ID", "subhaspace/TourismPackage")
MODEL_FILENAME = os.getenv("MODEL_FILENAME", "model.pkl")
ENCODER_FILENAME = os.getenv("ENCODER_FILENAME", "label_encoders.pkl")

@st.cache_resource
def load_artifacts():
    model_path = hf_hub_download(repo_id=MODEL_REPO_ID, filename=MODEL_FILENAME, repo_type="model")
    enc_path = hf_hub_download(repo_id=MODEL_REPO_ID, filename=ENCODER_FILENAME, repo_type="model")
    model = joblib.load(model_path)
    encoders = joblib.load(enc_path)
    return model, encoders

def encode_input(df, encoders):
    data = df.copy()
    for col, encoder in encoders.items():
        if col in data.columns:
            value = str(data.loc[0, col])
            classes = list(encoder.classes_)
            if value not in classes:
                value = classes[0]
            data[col] = encoder.transform([value])[0]
    return data

st.title("Tourism Package Purchase Prediction")

with st.form("prediction_form"):
    age = st.number_input("Age", min_value=18, max_value=100, value=35)
    typeofcontact = st.selectbox("Type of Contact", ["Company Invited", "Self Enquiry", "Self Inquiry"])
    citytier = st.selectbox("City Tier", [1, 2, 3])
    occupation = st.selectbox("Occupation", ["Salaried", "Small Business", "Large Business", "Free Lancer"])
    gender = st.selectbox("Gender", ["Male", "Female"])
    numberofpersonvisiting = st.number_input("Number of Persons Visiting", min_value=1, max_value=10, value=2)
    preferredpropertystar = st.selectbox("Preferred Property Star", [1, 2, 3, 4, 5])
    maritalstatus = st.selectbox("Marital Status", ["Single", "Married", "Divorced", "Unmarried"])
    numberoftrips = st.number_input("Number of Trips", min_value=0, max_value=20, value=2)
    passport = st.selectbox("Passport", [0, 1])
    owncar = st.selectbox("Own Car", [0, 1])
    numberofchildrenvisiting = st.number_input("Number of Children Visiting", min_value=0, max_value=6, value=0)
    designation = st.selectbox("Designation", ["Manager", "Senior Manager", "AVP", "VP", "Executive"])
    monthlyincome = st.number_input("Monthly Income", min_value=1000, max_value=500000, value=30000)
    pitchsatisfactionscore = st.slider("Pitch Satisfaction Score", min_value=1, max_value=5, value=3)
    productpitched = st.selectbox("Product Pitched", ["Basic", "Standard", "Deluxe", "Super Deluxe", "King"])
    numberoffollowups = st.number_input("Number of Followups", min_value=0, max_value=10, value=2)
    durationofpitch = st.number_input("Duration of Pitch", min_value=0, max_value=100, value=15)
    submitted = st.form_submit_button("Predict")

if submitted:
    input_df = pd.DataFrame([{
        "Age": age,
        "TypeofContact": typeofcontact,
        "CityTier": citytier,
        "Occupation": occupation,
        "Gender": gender,
        "NumberOfPersonVisiting": numberofpersonvisiting,
        "PreferredPropertyStar": preferredpropertystar,
        "MaritalStatus": maritalstatus,
        "NumberOfTrips": numberoftrips,
        "Passport": passport,
        "OwnCar": owncar,
        "NumberOfChildrenVisiting": numberofchildrenvisiting,
        "Designation": designation,
        "MonthlyIncome": monthlyincome,
        "PitchSatisfactionScore": pitchsatisfactionscore,
        "ProductPitched": productpitched,
        "NumberOfFollowups": numberoffollowups,
        "DurationOfPitch": durationofpitch
    }])

    model, encoders = load_artifacts()
    processed_df = encode_input(input_df, encoders)
    prediction = model.predict(processed_df)[0]

    if prediction == 1:
        st.success("This customer is likely to purchase the Wellness Tourism Package.")
    else:
        st.warning("This customer is unlikely to purchase the Wellness Tourism Package.")

    st.dataframe(input_df)
'''
with open(f"{DEPLOYMENT_PATH}/app.py", "w") as f:
    f.write(app_py)

requirements_txt = '''streamlit
pandas
scikit-learn
joblib
huggingface_hub
'''
with open(f"{DEPLOYMENT_PATH}/requirements.txt", "w") as f:
    f.write(requirements_txt)

dockerfile = '''FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY app.py /app/app.py

EXPOSE 7860

CMD ["streamlit", "run", "app.py", "--server.port=7860", "--server.address=0.0.0.0"]
'''
with open(f"{DEPLOYMENT_PATH}/Dockerfile", "w") as f:
    f.write(dockerfile)

push_script = '''from huggingface_hub import login, create_repo, upload_file
import os

HF_TOKEN = os.getenv("HF_TOKEN", "PASTE_YOUR_HF_TOKEN_HERE")
SPACE_REPO = "subhaspace/mloperations"

login(HF_TOKEN)
create_repo(repo_id=SPACE_REPO, repo_type="space", space_sdk="docker", exist_ok=True)

for filename in ["app.py", "requirements.txt", "Dockerfile"]:
    upload_file(
        path_or_fileobj=filename,
        path_in_repo=filename,
        repo_id=SPACE_REPO,
        repo_type="space"
    )

print("Deployment files uploaded to Hugging Face Space.")
'''
with open(f"{DEPLOYMENT_PATH}/push_to_space.py", "w") as f:
    f.write(push_script)

print("Deployment files created successfully.")

Deployment files created successfully.

### Observation
The deployment layer includes a Streamlit application, a Dockerfile, a dependencies file, and a helper script to push deployment files to Hugging Face Space. The application loads the saved model and encoder objects from the Hugging Face Model Hub and converts user inputs into a DataFrame before prediction.

## 5. MLOps Pipeline with GitHub Actions

In this section:
- a GitHub Actions workflow file is created,
- the workflow defines the major machine learning steps,
- the pipeline is configured to trigger on every push to the `main` branch.

In [25]:
pipeline_yml = '''
name: Tourism MLOps Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib huggingface_hub notebook nbconvert

      - name: Verify folder structure
        run: |
          ls -R

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute tourism_mlops_project_aligned.ipynb --output executed_tourism_mlops_project_aligned.ipynb

      - name: Upload executed notebook artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: executed_tourism_mlops_project_aligned.ipynb
'''
with open(f"{GITHUB_WORKFLOW_PATH}/pipeline.yml", "w") as f:
    f.write(pipeline_yml)

print("GitHub Actions workflow created successfully.")

GitHub Actions workflow created successfully.

### Observation
The GitHub Actions workflow automates the key stages of the machine learning process. It is triggered on every push to the `main` branch, which supports continuous integration and helps keep the workflow reproducible.

## 6. Output Evaluation

The final deliverables for evaluation are:
- Hugging Face Dataset link
- Hugging Face Model link
- Hugging Face Space link
- GitHub repository link
- Screenshots of:
  - repository folder structure,
  - executed GitHub Actions workflow,
  - running Streamlit application.

## 7. Project Links

Use these final links in your submission. Update only the GitHub repository link before exporting to HTML.

- Hugging Face Dataset: https://huggingface.co/datasets/subhaspace/TourismPackage
- Hugging Face Model: https://huggingface.co/subhaspace/TourismPackage
- Hugging Face Space: https://huggingface.co/spaces/subhaspace/mloperations
- GitHub Repository: https://github.com/your_github_username/your_repository_name

## 8. Final Insights

This project successfully implemented an end-to-end MLOps pipeline for Tourism Package Prediction. The solution covers dataset registration, direct data loading from the Hugging Face dataset space, data cleaning, train-test creation, model tuning, evaluation, model registration, deployment, and workflow automation.

The final system helps the business identify high-potential customers before outreach, improve targeting efficiency, and reduce manual effort. It also demonstrates how MLOps practices can make machine learning solutions reproducible, scalable, and deployment-ready.

### Final Submission Checklist
- Run all cells from top to bottom and ensure outputs are visible.
- Verify that the dataset, model, and Space links open correctly.
- Add screenshots of the GitHub folder structure, GitHub Actions workflow, and Streamlit app in the final report or keep them ready if separately required.
- Export the fully executed notebook to HTML before submission.